use_frameworks!

target 'NKInputFormKit_Example' do
  pod 'NKInputFormKit', :path => '../'
  pod 'NKModalViewManager'
  pod 'NKButton'

  target 'NKInputFormKit_Tests' do
    inherit! :search_paths

    
  end
end
